### ISSUE TITLE
Ensure API only responds with JSON even for error states

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/identity-enhancement-service#39]
Ensure that any unexpected error under /api/* will only ever have a response body containing json (unless explicitly documented).

404 currently triggers incorrect behaviour for example.

**Comment by smangelsdorf** [comment]
This is already the case for a *real* deployment, but the friendly development exception handler takes over and ignores the Accept header in the request when rendering the debugging information.

For errors that occur with `RAILS_ENV=production` this is already the case.

Can be simulated by applying:

```patch
diff --git i/config/environments/development.rb w/config/environments/development.rb
index df092d2..9ae7f19 100644
--- i/config/environments/development.rb
+++ w/config/environments/development.rb
@@ -1,11 +1,11 @@
 Rails.application.configure do
   config.cache_classes = false
   config.eager_load = false
-  config.consider_all_requests_local       = true
+  config.consider_all_requests_local       = false
   config.action_controller.perform_caching = false
   config.action_mailer.raise_delivery_errors = false
   config.active_support.deprecation = :log
   config.active_record.migration_error = :page_load
   config.assets.debug = true
-  config.assets.raise_runtime_errors = true
+  config.assets.raise_runtime_errors = false
 end
```

And then observing the output of a non-routable URL:

```json
$ curl --header 'Accept: application/json' http://localhost:8080/nonexistent/endpoint
{"status":"404","error":"Not Found"}
```

**Comment by smangelsdorf** [comment]
Need to test this again with `Accept: application/vnd.aaf.ide.v1+json`
