### ISSUE TITLE
API to access a list of the IdE Providers

### ISSUE THREAD

**Issue by okeeffeb** [ausaccessfed/identity-enhancement-service#48]
Service Providers need to be able to access a list of the IdE Providers ~~to make access control decisions based on the asserting organisation/project~~. Should be available in UI as well as via API.

**Comment by smangelsdorf** [comment]
Edited ticket content. Strikethrough is mine.

**Comment by smangelsdorf** [comment]
As the providers list is now public due to an unrelated change, the remaining part of this ticket is an API change.
