### ISSUE TITLE
Provider should be able to resolve the situation where an invitation has expired

### ISSUE THREAD

**Issue by smangelsdorf** [ausaccessfed/identity-enhancement-service#61]
Currently there's no way to address an expired invitation. Need to give some thought to:

* Do we allow providers to edit the expiry of an invitation before it expires?

    This may have implications for *other* providers who have provided an attribute but are expecting to be deleted by a certain date if the invitation hasn't been accepted.

* Do completely remove the invitation + placeholder Subject when it expires so the Subject can be reinvited (remembering we have audit trail information intact), or do we allow the existing invitation to be extended?

* Where should this functionality be shown the UI?

**Comment by bradleybeddoes** [comment]
Some random thoughts to progress discussion, no easy outs here really.

1. Would *other* providers know the date of expiry for the invite anyway?

2. Should we delete if only the one provider has enhanced the identity but leave intact if multiple providers have enhanced?

3. It seems like something the Subject view would contain but I wouldn't have thought a general provider would have access to that view?

**Comment by smangelsdorf** [comment]
1. I was thinking they would *have* to. If the Subject is pending, and may have its attributes removed at a future date, that should really be indicated in the UI when providing the attribute. Depends on the answer to (2)

2. That breaks the feature somewhat, and complicates the code. Essentially the only safe logic there would be "if two or more Providers have enhanced a pending Subject, the invitation is made to never expire". I'm not sure if that fits the bill.

3. There is no Subject view currently. Easy enough to add one, but I guess the correct location in the UI depends on what the functionality actually is.

**Comment by bradleybeddoes** [comment]
I am fine for 1 to discount 2. In this scenario other providers should have the option to resend invites assuming 'Andrew McGregor' got an invite 2 weeks ago from provider A and subsequently 'lost it' provider B should have the ability to resend it.

This would also probably mean that resending an invite should extend the expiry period - thoughts?

A subject view, at least for super admins would be a good thing, inline with SPIN impl.

**Comment by smangelsdorf** [comment]
So the changes are:

1. Subject attributes will be removed when the invitation expires - #56 
2. When any Provider is adding attributes to a pending Subject, they will be told about the expiry
3. New Subject UI, super admin only (pending later review)
4. Provider needs the ability to resend an invitation to a Subject
5. Need the ability to "reinvite" a Subject whose invitation has expired. I am thinking this will remove the pending Subject and create a new one.

Cool?

**Comment by bradleybeddoes** [comment]
Should we be deleting the Subject as well when expiry occurs? We didn't settle on this and it impacts 5.

**Comment by smangelsdorf** [comment]
Yeah. I have to play with that a bit and find a reliable way to do it which doesn't introduce a race condition. One way or another (5) will involve the creation of a new pending Subject, and the originally invited Subject will no longer exist.

Invitation#subject will need to become nullable if it isn't already, so we can still track the expired Invitation after deleting the pending Subject to show the invitations/expired view.

**Comment by bradleybeddoes** [comment]
1 - 5: assured

**Comment by smangelsdorf** [comment]
Regarding (5), this won't be necessary as we'll regularly be sweeping away expired invitations. Inviting somebody again after their invitation has expired will be as easy as just inviting them again.
