### ISSUE TITLE
Providers link in UI is not applicable

### ISSUE THREAD

**Issue by okeeffeb** [ausaccessfed/identity-enhancement-service#68]
The Providers link, which is accessible from the Providers' View Provider page, links to Forbidden. This is possible from Roles 9as per example image), API Accounts and Provided Attributes.
![providers link - roles table in ui](https://cloud.githubusercontent.com/assets/10039508/7014386/a03bd38a-dd07-11e4-9797-81f146117c1c.png)

**Comment by smangelsdorf** [comment]
This is actually triggered by an incorrect permission in the provider default roles. The permission `providers:PROVIDER_ID:list` (replaced by the numeric ID) should actually be `providers:list`.

Arguably, the providers list could be a public action (available to all authenticated subjects), which would also solve this problem.

Thoughts @bradleybeddoes ?

**Comment by bradleybeddoes** [comment]
It won't be able to be public unfortunately due to #57

**Comment by smangelsdorf** [comment]
#57 already requires that this view be filtered based on public/private (i.e. excluding private providers that the current user doesn't have access to), so the question is simply:

Should the list of public providers be visible to:

* Anyone using IdE, or
* Only people with some kind of access to a provider.

**Comment by okeeffeb** [comment]
#51 suggests it may need to be the first option; Anyone using IdE
By this point providers should have set themselves public or private

On Thu, Apr 16, 2015 at 10:32 AM, Shaun Mangelsdorf <
notifications@github.com> wrote:

> #57
> <https://github.com/ausaccessfed/identity-enhancement-service/issues/57>
> already requires that this view be filtered based on public/private (i.e.
> excluding private providers that the current user doesn't have access to),
> so the question is simply:
>
> Should the list of public providers be visible to:
>
>    - Anyone using IdE, or
>    - Only people with some kind of access to a provider.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ausaccessfed/identity-enhancement-service/issues/68#issuecomment-93606304>
> .
>



-- 

*Brendan O’Keeffe *| Project Manager | *Australian Access Federation Inc*

*Mobile: *+61 412 275 150 | *Email*: <Heath.Marks@aaf.edu.au>
brendan.okeeffe@aaf.edu.au | *Support: *http://support.aaf.edu.au

*Mail: PO Box 2104 | Kelvin Grove, QLD 4059 | Australia*

PRIVILEGED – PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the
use of the addressee(s) and may contain information which is confidential
or privileged.  If you receive this email and you are not the addressee(s)
[or responsible for delivery of the email to the addressee(s)], please
disregard the contents of the email, delete the email and notify the author
immediately.

**Comment by bradleybeddoes** [comment]
@smangelsdorf In that case if you've already applied filtering to remove private providers I'm happy for the remaining list to be visible to all.

@okeeffeb FYI responding to tickets via email screws with the system so I have edited your comment. If you could use the web UI only that would be great.
