### ISSUE TITLE
Change the Provider label 

### ISSUE THREAD

**Issue by okeeffeb** [ausaccessfed/identity-enhancement-service#70]
As the federation already consists of many types of providers (Service Providers, Identity Providers, Attribute Providers), can we use something more unique and/or descriptive than 'IdE Provider' or just  'Provider'? 

Users will not always be from an 'Organisation' (e.g a research project, or collaborative group) which could also get confused with current federation terminology. 

Suggestion:  'Issuer' or "Attribute Issuer", if this fits with current terminology.

**Comment by smangelsdorf** [comment]
"Issuer" has a different connotation in SAML, which isn't appropriate here. IdE is the Issuer of a SAML assertion which contains the attributes that have been given to enhance an identity.

"Asserter" is another term I've heard thrown around, but for a similar reason it is ambiguous. IdE acts as the asserter, in that it creates the assertion I mentioned above.

"Provider" is suboptimal but the least confusing of the three in my opinion. Happy to consider other alternatives.

There was considerable thought/discussion given to this before the IdE project started.

cc @bradleybeddoes if you want to weigh in on this.

**Comment by bradleybeddoes** [comment]
I am personally comfortable with Provider, I feel it fits the rest of the space reasonably well.

However we could be more explicit and refer to them as 'Identity Enhancement Provider(s)'. In which case:

* Service Providers: Provide services to the federation
* Identity Providers: Provide user identities to the federation
* Identity Enhancement Providers: Enhance user identities and provide this to the federation

I see nothing that indicates a Provider/Identity Enhancement Provider is supposed to be an organisation or specific subscriber. In fact I've quite deliberately ensured that was never communicated as the case from well before serious conversation/planning/design for IdE undertaken.

**Comment by smangelsdorf** [comment]
Reclassified as a documentation issue. "Provider" in itself is not ambiguous in the context of IdE, so the UI won't need to change.

We may adjust the "full name" of Provider to be "Identity Enhancement Provider" or just "Enhancement Provider" when discussed in documentation.

**Comment by bradleybeddoes** [comment]
To ensure all parties are happy any relevant documentation can refer to:

* Enhancement Providers: Those folks who actually enhance identities (shown simply as providers within the UI)
* Enhancement Consumers: Systems that consume enhanced identity data via SAML or RESTful APIs.
